### ISSUE TITLE
You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by MiguelSavignano** [RafalFilipek/styled-props#7]
When compile my app with webpack and babel.

ERROR in ./~/styled-props/src/styledProps.js
Module parse failed: /node_modules/styled-props/src/styledProps.js Unexpected token (3:5)

 // @flow
|
| type PropsLike = { [key:string]: any };
| type MapperFunction = (props:PropsLike) => any;
| export type StyledPropsFunction = (map:PropsLike, fallback?:string) => MapperFunction;
 @ ./~/styled-props/src/index.js 1:0-40

**Comment by RafalFilipek** [comment]
Hey @MiguelSavignano!
In v0.2.0 (just released) `module` and `jsnext:main` keys were removed from `package.json` (for now). Can you check it now?

**Comment by MiguelSavignano** [comment]
Thank you @RafalFilipek I checked it and works.
